# Cloudflare Pages Configuration
name = "clerkship"
compatibility_date = "2024-01-01"

# Pages configuration - use .next directory for Next.js
pages_build_output_dir = ".next"

# Build configuration
[build]
command = "DATABASE_URL=$DATABASE_URL npm run build"

[env.production]
# Environment variables are set in Cloudflare dashboard
